# Generated by Django 4.2.2 on 2023-06-19 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swizzleapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='favorites',
            field=models.ManyToManyField(related_name='recipes', through='swizzleapi.Favorite', to='swizzleapi.mixologist'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ratings',
            field=models.ManyToManyField(related_name='recipes_rated', through='swizzleapi.Rating', to='swizzleapi.mixologist'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='mixologist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_favorite_recipes', to='swizzleapi.mixologist'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_favorite_recipes', to='swizzleapi.recipe'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swizzleapi.recipe'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image_url',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='original_link',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
