# Generated by Django 4.2.2 on 2023-06-21 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swizzleapi', '0002_recipe_favorites_recipe_ratings_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='review',
        ),
    ]
