# Generated by Django 4.2.2 on 2023-06-21 19:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swizzleapi', '0004_remove_rating_score_rating_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MaxValueValidator(5)]),
        ),
    ]
